---
title: "<center>Anjing Liu"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---
## EDUCATION
### **Tianjin University, School of Life Sciences**
***Bachelor of Biological Sciences 09/2017-07/2021***  

**Overall GPA**:  3.55/4.0    
**English Test Results**: CET-6, TOEFL 104(Speaking 23)    
**Computer Skills**: R, Matlab, SQL   
**Award**:    Second Prize of Basic Experimental Skills Competition   
Excellent Students Awards of Tianjin University

## RESEARCH  EXPERIENCES
### **Tianjin University**
***Advisor: Professor Sheng Wang 10/2020-7/2021***   

-Research on Metal Sulfide Catalyst MoS~2~ for Enhanced Chemokinetic Tumor Therapy.    
-Aim to improve the effect of chemokinetic therapy.    
-Learned the synthesis and characterization methods of MoS~2~.    
-Studies the process of MoS~2~ promoting the conversion of Fe^3+^ to Fe^2+^.    
-Learned the principles of chemical kinetics.    
-Learned the experimental design of tumor treatment.    


### **Tsinghua University**
***Advisor: Ph.D. Jie Li 10/2019-12/2019***

-Analyze Cancer Single-Cell Data and Tumor Immunological Mechanism.   
-Applied Back-SPIN to cluster cell expression profiles and identify the labeled gene of specific cells.   
-Identified different types of immune cells through the enrichment of labeled genes.
-Revealed the relationship between different types of cells by heat maps.   
-Identified malignant tumor cells by dividing the mutant transcripts within the cell.   
-Determined different types of malignant tumor cells through the random forest algorithm, and studied the relationship between different types of malignant tumor cells and immune cells.   
-Identified the immunological mechanisms to find the gene affecting malignant tumor cells.


## INTERNSHIPS                                                                                                                                                                 
### **Tianjin International Joint Academy of Biomedicine**	

***Advisor: Associate Professor Cheng Chen 08/2019- 09/2019***

-The mechanism and drug development of Amyotrophic Lateral Sclerosis.     
-Learned the pathogenesis of ALS mainly including gene mutation, oxidative stress, excitotoxicity, mitochondrial abnormalities and immune inflammatory response.   
-Learned Oxidative stress being involved in the onset and development of amyotrophic lateral sclerosis (ALS).  Learned edaravone being a free radical scavenger can reduce the effect of oxidative stress.   
-Studied the mechanism of edaravone in the treatment of ALS (may also be through scavenging free radicals and inhibiting oxidative stress, thereby producing a protective effect).


### **Bioscience (Tianjin) Diagnostic Technology Co.,Ltd** 	

***Advisor: Associate Professor Xiaoqun Gong 07/2019- 08/2019***

-Determination of cardiac troponin I (cTnI) concentration by Sandwich ELISA.   
-Used fluorescence immunoassay analyzer Axceed P100 for blood sample detection.   
-Obtained the concentration of cardiac troponin I, and determined the risk of myocardial damage in patients with coronary syndrome.